---
title: "Statistical Analysis for Neural and Cognitive Correlates of Performance Manuscript"
author: "Zachariah Cross and Chloe Dziego"
date: "02/07/2021"
output:
  html_document: default
  pdf_document: default
editor_options: 
  chunk_output_type: console
---


```{r global-options, include=FALSE}

knitr::opts_chunk$set(fig.width=10, fig.height=6,
                      echo=FALSE, warning=FALSE, message=FALSE)

library(plyr)
library(tidyverse)
library(hrbrthemes)
library(ggpubr)
library(lme4)
library(car)
library(corrplot)
library(RColorBrewer)
library(effects)
library(modelr)
library(rlang)
library(splines)
library(lmerTest)
library(mgcv)
library(colorspace)
library(broom.mixed)
library(ranger)
library(skimr)
library(caret)
library(ordinalForest)
library(VGAM)
library(mgcv)

```

```{r raincloud plot function}

# Defining the geom_flat_violin function ----
# Note: the below code modifies the
# existing github page by removing a parenthesis in line 50
"%||%" <- function(a, b) {
  if (!is.null(a)) a else b
}
geom_flat_violin <- function(mapping = NULL, data = NULL, stat = "ydensity",
                             position = "dodge", trim = TRUE, scale = "area",
                             show.legend = NA, inherit.aes = TRUE, ...) {
  layer(
    data = data,
    mapping = mapping,
    stat = stat,
    geom = GeomFlatViolin,
    position = position,
    show.legend = show.legend,
    inherit.aes = inherit.aes,
    params = list(
      trim = trim,
      scale = scale,
      ...
    )
  )
}
#' @rdname ggplot2-ggproto
#' @format NULL
#' @usage NULL
#' @export
GeomFlatViolin <-
  ggproto("GeomFlatViolin", Geom,
          setup_data = function(data, params) {
            data$width <- data$width %||%
              params$width %||% (resolution(data$x, FALSE) * 0.9)
            # ymin, ymax, xmin, and xmax define the bounding rectangle for each group
            data %>%
              group_by(group) %>%
              mutate(
                ymin = min(y),
                ymax = max(y),
                xmin = x,
                xmax = x + width / 2
              )
          },
          draw_group = function(data, panel_scales, coord) {
            # Find the points for the line to go all the way around
            data <- transform(data,
                              xminv = x,
                              xmaxv = x + violinwidth * (xmax - x)
            )
            # Make sure it's sorted properly to draw the outline
            newdata <- rbind(
              plyr::arrange(transform(data, x = xminv), y),
              plyr::arrange(transform(data, x = xmaxv), -y)
            )
            # Close the polygon: set first and last point the same
            # Needed for coord_polar and such
            newdata <- rbind(newdata, newdata[1, ])
            ggplot2:::ggname("geom_flat_violin", GeomPolygon$draw_panel(newdata, panel_scales, coord))
          },
          draw_key = draw_key_polygon,
          default_aes = aes(
            weight = 1, colour = "grey20", fill = "white", size = 0.5,
            alpha = NA, linetype = "solid"
          ),
          required_aes = c("x", "y")
  )

```

Prepare data frames

```{r read in behav data and prepare for analysis}

# read in the preprocessed .csv file
# drop subject PR14 as they are an outlier on CRUSE
final_data <- read_csv("final_data.csv")

# filter the data to only look at the test CRUSE session
d_test <- final_data # %>% 
#  filter(session == "test")

# we need to remove the duplicate data points
d_test_unique <- d_test %>% 
  select(subj, TPE, Time, tma_rt, DSpanScore, VSL_accuracy, threedStimulus.ACC, threedStimulus.RT, Intercept, Slope, paf, cog, session) %>% 
  distinct()
  
dim(d_test)
dim(d_test_unique)

# remove additional duplicates for TPE
d_tpe <- d_test_unique %>% 
  select(subj,TPE,Time,paf,VSL_accuracy,Slope,Intercept,DSpanScore,threedStimulus.ACC,threedStimulus.RT,cog,session) %>%
  filter(subj != "PR14") %>%
  rename(MR_ACC = threedStimulus.ACC)  %>%
  rename(MR_RT = threedStimulus.RT)  %>%
  distinct()

d_tpe <- na.omit(d_tpe) %>%
  filter(subj != "PR39" & subj != "PR05")

unique(d_tpe$subj)

# data frame just for reaction time
d_tpe_rt <- d_test_unique %>% 
  select(subj,tma_rt,Time,paf,VSL_accuracy,Slope,Intercept,DSpanScore,threedStimulus.ACC,threedStimulus.RT,cog,session) %>%
  filter(subj != "PR14") %>%
  rename(MR_ACC = threedStimulus.ACC)  %>%
  rename(MR_RT = threedStimulus.RT)  %>%
  distinct()

d_tpe_rt <- na.omit(d_tpe_rt)

# create an aggregated data frame to look at associations between control and resting state variables and CRUSE
TPE_Grand <- d_tpe %>%
  select(subj,TPE,paf,VSL_accuracy,DSpanScore,Slope,MR_ACC,Intercept,MR_RT,cog,session) %>%
  group_by(subj,session) %>%
  summarise_all(funs(mean), na.rm = TRUE)

# create an aggregated data frame to look at TMA reaction time between testing sessions
TPE_Grand_RT <- d_tpe_rt %>%
  select(subj,tma_rt,paf,VSL_accuracy,DSpanScore,Slope,MR_ACC,Intercept,MR_RT,cog,session) %>%
  group_by(subj,session) %>%
  summarise_all(funs(mean), na.rm = TRUE)

group_labels <- c("Practice", "Test")

rain_tpe <- ggplot(data = TPE_Grand, aes(y = TPE, x = session, fill = session)) +
  geom_flat_violin(position = position_nudge(x = .2, y = 0), alpha = .65) +
  geom_point(aes(y = TPE, color = session), position = position_jitter(width = .15), size = 3, alpha = 0.3) +
  scale_y_continuous(limits = c(2000, 12000), breaks = seq(2000, 12000, by = 2000)) +
  geom_boxplot(width = .1, outlier.shape = NA, alpha = 0.5) +
  scale_color_manual(values = c("turquoise4", "tan1"), labels=group_labels, name = "Session") +
  scale_fill_manual(values = c("turquoise4", "tan1"), labels=group_labels, name = "Session") +
  xlab("Session") + ylab ("Tactical Picture Error") +
  theme_bw() +
  theme(axis.title.x = element_text(size=14),
                  plot.title = element_text(size=14, face="bold"),
                  axis.title.y = element_text(size=14),
                  axis.text.x = element_text(size=12),
                  axis.text.y = element_text(size=12))

rain_tpe

rain_rt <- ggplot(data = TPE_Grand_RT, aes(y = tma_rt, x = session, fill = session)) +
  geom_flat_violin(position = position_nudge(x = .2, y = 0), alpha = .65) +
  geom_point(aes(y = tma_rt, color = session), position = position_jitter(width = .15), size = 1, alpha = 0.3) +
  scale_y_continuous(limits = c(15, 350), breaks = seq(0, 350, by = 50)) +
  geom_boxplot(width = .1, outlier.shape = NA, alpha = 0.5) +
  scale_color_manual(values = c("turquoise4", "tan1"), labels=group_labels, name = "Session") +
  scale_fill_manual(values = c("turquoise4", "tan1"), labels=group_labels, name = "Session") +
  xlab("Session") + ylab ("TMA Reaction Time [s]") +
  theme_bw() +
  theme(axis.title.x = element_text(size=14),
                  plot.title = element_text(size=14, face="bold"),
                  axis.title.y = element_text(size=14),
                  axis.text.x = element_text(size=12),
                  axis.text.y = element_text(size=12))

rain_rt

avg_time_tpe <- d_tpe %>%
  select(TPE,Time,session) %>%
  group_by(Time,session) %>%
  summarise(mean_TPE = mean(TPE),
            se = (sd(TPE))/sqrt(n())) %>% 
  mutate(Time = as.numeric(Time))

tpe_time <- ggplot(avg_time_tpe, aes(x=Time, y=mean_TPE, fill=session))+
  geom_smooth(color="black", size=0.5) +
  scale_color_manual(values = c("turquoise4", "tan1"), labels=group_labels, name = "Session") +
  scale_fill_manual(values = c("turquoise4", "tan1"), labels=group_labels, name = "Session") +
  xlab("Time [20s]") + ylab ("Mean Tactical Picture Error") +
  scale_y_continuous(limits = c(1000, 12000), breaks = seq(1000, 12000, by = 2000)) +
  scale_x_continuous(limits = c(300, 2660), breaks = seq(300, 2660, by = 500)) +
  theme_bw() +
  theme(axis.title.x = element_text(size=14),
                  plot.title = element_text(size=14, face="bold"),
                  axis.title.y = element_text(size=14),
                  axis.text.x = element_text(size=12),
                  axis.text.y = element_text(size=12))

tpe_time

tiff("rain_clouds.tiff", units="in", width=10, height=4, res=300)
ggarrange(rain_tpe, tpe_time,
          labels = c("A", "B"),
          ncol = 2, nrow = 1,
          common.legend = TRUE)
dev.off()

# get descriptives
my_fun <- function(x, num_var){
  num_var <- enquo(num_var)

  x %>%
    summarize(avg = mean(!!num_var), n = n(), 
              sd = sd(!!num_var), se = sd/sqrt(n))
}


descriptives <- TPE_Grand %>%
  select(subj,TPE,VSL_accuracy,DSpanScore,Slope,MR_ACC,Intercept,MR_RT,cog,session)

descriptives %>%
  group_by(session) %>%
  my_fun(TPE)

descriptives %>% 
  filter(session=="practice") %>% 
  summary(TPE_Grand$TPE)

descriptives %>% 
  filter(session=="test") %>% 
  summary(TPE_Grand$TPE)
  
control_tasks <- descriptives %>%
  filter(session == "practice") %>%
  select(-session)

mean(control_tasks$VSL_accuracy)
sd(control_tasks$VSL_accuracy)
summary(control_tasks$VSL_accuracy)

mean(control_tasks$DSpanScore)
sd(control_tasks$DSpanScore)
summary(control_tasks$DSpanScore)

mean(control_tasks$MR_ACC)
sd(control_tasks$MR_ACC)
summary(control_tasks$MR_ACC)

mean(control_tasks$MR_RT)
sd(control_tasks$MR_RT)
summary(control_tasks$MR_RT)

rain_cog <- ggplot(data = subset(TPE_Grand, session == "practice"), aes(y = cog, x = session, fill = session)) +
  geom_flat_violin(position = position_nudge(x = .2, y = 0), alpha = .65) +
  geom_point(aes(y = cog, color = session), position = position_jitter(width = .15), size = 3, alpha = 0.3) +
  geom_boxplot(width = .1, outlier.shape = NA, alpha = 0.5) +
  scale_color_manual(values = c("black")) +
  scale_fill_manual(values = c("black")) +
  ylab ("Individual Alpha Frequency [Hz]") +
  theme_bw() +
  theme(legend.position = "none",
                  plot.title = element_text(size=14, face="bold"),
        axis.title.x=element_blank(),
        axis.text.x=element_blank(),
        axis.ticks.x=element_blank(),
        axis.title.y = element_text(size=16),
        axis.text.y = element_text(size=16))

rain_cog

rain_slope <- ggplot(data = subset(TPE_Grand, session == "practice"), aes(y = Slope, x = session, fill = session)) +
  geom_flat_violin(position = position_nudge(x = .2, y = 0), alpha = .65) +
  geom_point(aes(y = Slope, color = session), position = position_jitter(width = .15), size = 3, alpha = 0.3) +
  geom_boxplot(width = .1, outlier.shape = NA, alpha = 0.5) +
  scale_color_manual(values = c("salmon")) +
  scale_fill_manual(values = c("salmon")) +
  ylab ("1/f Slope") +
  theme_bw() +
  theme(legend.position = "none",
                  plot.title = element_text(size=14, face="bold"),
        axis.title.x=element_blank(),
        axis.text.x=element_blank(),
        axis.ticks.x=element_blank(),
        axis.title.y = element_text(size=16),
        axis.text.y = element_text(size=16))

rain_slope

rain_intecept <- ggplot(data = subset(TPE_Grand, session == "practice"), aes(y = Intercept, x = session, fill = session)) +
  geom_flat_violin(position = position_nudge(x = .2, y = 0), alpha = .65) +
  geom_point(aes(y = Intercept, color = session), position = position_jitter(width = .15), size = 3, alpha = 0.3) +
  geom_boxplot(width = .1, outlier.shape = NA, alpha = 0.5) +
  scale_color_manual(values = c("#69b3a2")) +
  scale_fill_manual(values = c("#69b3a2")) +
  ylab ("1/f Intercept") +
  theme_bw() +
  theme(legend.position = "none",
                  plot.title = element_text(size=14, face="bold"),
        axis.title.x=element_blank(),
        axis.text.x=element_blank(),
        axis.ticks.x=element_blank(),
        axis.title.y = element_text(size=16),
        axis.text.y = element_text(size=16))

rain_intecept

tiff("rain_clouds_eeg.tiff", units="in", width=12, height=4, res=300)
ggarrange(rain_cog, rain_slope, rain_intecept,
          labels = c("A", "B", "C"),
          ncol = 3, nrow = 1,
          common.legend = F)
dev.off()

```

```{r plot TPE scores for each subject across time}

tiff("globa_tpe.tiff", units="in", width=8, height=4, res=300)
ggplot(d_tpe, aes(x = Time, y = TPE)) +
  geom_line(aes(colour = subj)) +
  facet_grid(~session)
dev.off()

tiff("subj_tpe.tiff", units="in", width=8, height=4, res=300)
ggplot(d_tpe, aes(x = Time, y = TPE)) +
  geom_line(color="#69b3a2") +
  facet_grid(subj~session)
dev.off()

```

```{r extract individual regression slopes between TPE and Time for first 500 seconds}

# extract the individual regression slopes for TPE and Time
# start with the practice session
regression_data_practice <- d_tpe %>%
  select(subj, TPE, Time, session) %>%
  filter (session == "practice" & Time < 500) %>%
  select(-session)

regression_data_test <- d_tpe %>%
  select(subj, TPE, Time, session) %>%
  filter (session == "test" & Time < 500) %>%
  select(-session)

tpe_coefs_practice = c()

for (i in c(unique(regression_data_practice$subj))) {
  # Create temporary data frame:
  tpe_tmp <- regression_data_practice[regression_data_practice$subj==i,]
  # Perform regression:
  reg_result <- lm(tpe_tmp$TPE ~ tpe_tmp$Time)
  # Get coefficient:
  tmp_coef <- coef(reg_result)
  # Store coefficient:
  tpe_coefs_practice[i] <- tmp_coef[2]
}

tpe_coefs_test = c()

for (i in c(unique(regression_data_test$subj))) {
  # Create temporary data frame:
  tpe_tmp <- regression_data_test[regression_data_test$subj==i,]
  # Perform regression:
  reg_result <- lm(tpe_tmp$TPE ~ tpe_tmp$Time)
  # Get coefficient:
  tmp_coef <- coef(reg_result)
  # Store coefficient:
  tpe_coefs_test[i] <- tmp_coef[2]
}

declinet <- data.frame(tpe_coefs_test) %>%
  rownames_to_column(var = "subj") %>%
  mutate(session = "test") %>%
  rename(decline = "tpe_coefs_test")

declinep <- data.frame(tpe_coefs_practice) %>%
  rownames_to_column(var = "subj") %>%
  mutate(session = "practice") %>%
  rename(decline = "tpe_coefs_practice")

decline <- full_join(declinet, declinep)

# now filter the original data frame to remove the first 500 seconds and join the "decline" data frame to the model

d_tpe_final <- d_tpe %>%
  filter(Time >= 500) %>%
  left_join(decline, by = c("subj", "session"))

```

``` {r decline plots}

cor_slope_tpe <- d_tpe_final %>% 
  select(subj,session,TPE,decline) %>%
  group_by(subj,session) %>%
  summarise_all(funs(mean), na.rm = TRUE) %>% 
  mutate(Session = factor(session, levels = c("practice","test"), labels = c("Practice", "Test")))

scatter_tpe <- ggplot(cor_slope_tpe, aes(decline,TPE), color = session) +
  geom_point(aes(colour = session), shape=20, size = 5) +
  scale_color_manual(values=c("turquoise4", "tan1")) +
  labs(y="Mean TPE from 500 Seconds", x = "Mean TPE Decline from 0 - 500 Seconds") +
  geom_smooth(method=lm,  linetype="solid",
              color="gray48", fill="darkgrey") +
  ggtitle("Relationship Between TPE Scores", subtitle = "by session") +
  facet_grid(~Session) +
  theme_bw() + 
  theme(legend.position="none",
        legend.text = element_text(size = 14, colour = "black"),
        legend.title = element_text(size = 12, colour = "black"),
        panel.border = element_rect(color="black", fill=NA, size = 1), 
        strip.background = element_rect(fill="gray", color="black"), 
        strip.text.x = element_text(size = 12, colour = "black"),
        strip.text.y = element_text(size = 12, colour = "black"),
        axis.text = element_text(size = 12),
        plot.title = element_text(size = 16, face = "bold"),
        axis.title = element_text(size = 16))

tpe_schematic <- d_tpe %>% 
  filter(subj =="PR17" | subj =="PR21" | subj =="PR27" | subj =="PR42") %>% 
  mutate(subj = factor(subj, levels = c("PR17","PR21","PR27","PR42"),labels=c("Participant 1","Participant 2", "Participant 3","Participant 4"))) %>% 
  mutate(Session = factor(session, levels = c("practice","test"), labels = c("Practice", "Test")))

tpe_example <- ggplot(tpe_schematic, aes(x = Time, y = TPE)) +
  geom_line(aes(colour = Session, linetype = Session), size = 1) +
  scale_color_manual(values=c("turquoise4", "tan1"), name = "Session") +
  scale_linetype_manual(values=c("dashed","solid")) +
  labs(y="Tactical Picture Error", x = "Experimental Time [20s epochs]") +
  ggtitle("Individual TPE Slopes", subtitle = "by session") +
  facet_wrap(~subj) +
  scale_y_continuous(breaks = c(0, 5000, 10000, 15000)) +
  annotate("rect", fill = "grey", alpha = 0.4, 
        xmin = 0, xmax = 500,
        ymin = -Inf, ymax = Inf) +
  theme_light() +
  theme(legend.position="right",
        legend.text = element_text(size = 14, colour = "black"),
        legend.title = element_text(size = 12, colour = "black"),
        panel.border = element_rect(color="black", fill=NA, size = 1), 
        strip.background = element_rect(fill="gray", color="black"), 
        strip.text.x = element_text(size = 12, colour = "black"),
        strip.text.y = element_text(size = 12, colour = "black"),
        axis.text = element_text(size = 12),
        plot.title = element_text(size = 16, face = "bold"),
        axis.title = element_text(size = 16))

tiff("tpe_schematic_methods_plots.tiff", units="in", width=15, height=6, res=300)
ggarrange(tpe_example, scatter_tpe,
          labels = c("A", "B"),
          ncol = 2, nrow = 1,
          common.legend = T)
dev.off()

```

## Linear mixed-effects models with cubic splines

```{r lmer modelling for neural and behavioural predictors}

library(emmeans)
library(ggeffects)
#library(performance)

# set contrasts
options(contrasts = c("contr.Sum","contr.helmert"))
options(decorate.contr.Treatment="",decorate.contr.Sum="",decorate.contrasts=c("[", "]"))

# aperiodic slope

# get minimum, mean and maximum values for our predictor variables
summary(d_tpe_final$Slope)

lmer_slope <- lmer(TPE ~ ns(Time, 4) * Slope * session + decline + (1 | subj), data = d_tpe_final)

Anova(lmer_slope)
summary(lmer_slope)
model_performance(lmer_slope)
check_model(lmer_slope)

data_slope <- ggemmeans(lmer_slope,
                     terms = c("Time [all]", "Slope [-1.90, -1.04, -0.31]", "session"),
                     ci.lvl = 0.83)

lmer_slope.effects <- data_slope %>% 
  as_tibble() %>% 
  mutate(Slope = factor(group, labels = c("Steep","Moderate","Flatter")))

spline_slope <- ggplot(lmer_slope.effects, aes(x,predicted, ymin = conf.low, ymax = conf.high)) +
  geom_line(aes(linetype=Slope)) +
  scale_linetype_manual(values=c("solid", "longdash", "solid")) +
  scale_fill_manual(values = c("turquoise4", "tan1","black")) +
  geom_ribbon(aes(fill=Slope),alpha=0.5) +
  facet_grid(~facet) +
  ylab("Tactical Picture Error") +
  scale_y_continuous(breaks = c(0, 2000, 4000, 6000, 8000)) +
  xlab("Time [20s]") +
  theme_bw() +
  theme(legend.position="top",
        legend.text = element_text(size = 14),
        legend.title = element_text(size = 14),
        axis.title.x = element_text(size=16),
        plot.title = element_text(size=16, face="bold"),
        axis.title.y = element_text(size=16),
        axis.text.x = element_text(size=16),
        axis.text.y = element_text(size=16),
        strip.text.x = element_text(size = 14))

spline_slope

# aperiodic intercept
summary(d_tpe_final$Intercept)

lmer_intercept <- lmer(TPE ~ ns(Time, 4) * Intercept * session + decline + (1 | subj), data = d_tpe_final)
Anova(lmer_intercept)
summary(lmer_intercept)
model_performance(lmer_intercept)
check_model(lmer_intercept)

data_intercept <- ggemmeans(lmer_intercept,
                     terms = c("Time [all]", "Intercept [-26.24, -21.57, -17.95]", "session"),
                     ci.lvl = 0.83)

lmer_intercept.effects <- data_intercept %>% 
  as_tibble() %>% 
  mutate(Intercept = factor(group, labels = c("High","Moderate","Low")))

spline_intercept <- ggplot(lmer_intercept.effects, aes(x, predicted, ymin = conf.low, ymax = conf.high)) +
  geom_line(aes(linetype=Intercept)) +
  scale_linetype_manual(values=c("solid", "longdash", "solid")) +
  scale_fill_manual(values = c("turquoise4", "tan1","black")) +
  geom_ribbon(aes(fill=Intercept),alpha=0.5) +
  facet_grid(~facet) +
  ylab("Tactical Picture Error") +
  scale_y_continuous(breaks = c(0, 2000, 4000, 6000, 8000)) +
  xlab("Time [20s]") +
  theme_bw() +
  theme(legend.position="top",
        legend.text = element_text(size = 14),
        legend.title = element_text(size = 14),
        axis.title.x = element_text(size=16),
        plot.title = element_text(size=16, face="bold"),
        axis.title.y = element_text(size=16),
        axis.text.x = element_text(size=16),
        axis.text.y = element_text(size=16),
        strip.text.x = element_text(size = 14))

spline_intercept

# individual alpha frequency
summary(d_tpe_final$cog)

lmer_cog <- lmer(TPE ~ ns(Time, 4) * cog * session + decline + (1 | subj), data = d_tpe_final)
Anova(lmer_cog)
summary(lmer_cog)
model_performance(lmer_cog)
check_model(lmer_cog)

data_cog <- ggemmeans(lmer_cog,
                     terms = c("Time [all]", "cog [8.50, 10.00, 11.00]", "session"),
                     ci.lvl = 0.83)

lmer_cog.effects <- data_cog %>% 
  as_tibble() %>% 
  mutate(IAF = factor(group, labels = c("Low","Moderate","High")))

spline_iaf <- ggplot(lmer_cog.effects, aes(x, predicted, ymin = conf.low, ymax = conf.high)) +
  geom_line(aes(linetype=IAF)) +
  scale_linetype_manual(values=c("solid", "longdash", "solid")) +
  scale_fill_manual(values = c("turquoise4", "tan1","black")) +
  geom_ribbon(aes(fill=IAF),alpha=0.5) +
  facet_grid(~facet) +
  ylab("Tactical Picture Error") +
  scale_y_continuous(breaks = c(0, 2000, 4000, 6000, 8000)) +
  xlab("Time [20s]") +
  theme_bw() +  
  theme(legend.position="top",        
        legend.text = element_text(size = 14),
        legend.title = element_text(size = 14),
        axis.title.x = element_text(size=16),
        plot.title = element_text(size=16, face="bold"),
        axis.title.y = element_text(size=16),
        axis.text.x = element_text(size=16),
        axis.text.y = element_text(size=16),
        strip.text.x = element_text(size = 14))

spline_iaf

tiff("spline_lmer_models.tiff", units="in", width=18, height=5, res=300)
ggarrange(spline_iaf, spline_slope, spline_intercept,
          labels = c("A", "B", "C"),
          ncol = 3, nrow = 1,
          common.legend = FALSE)
dev.off()

# visual statistical learning ability
summary(d_tpe_final$VSL_accuracy)

lmer_vsl <- lmer(TPE ~ ns(Time, 4) * VSL_accuracy * session + decline + (1 | subj), data = d_tpe_final)
Anova(lmer_vsl)
summary(lmer_vsl)
model_performance(lmer_vsl)
check_model(lmer_vsl)

data_vsl <- ggemmeans(lmer_vsl,
                     terms = c("Time [all]", "VSL_accuracy [0.31, 0.62, 1.00]", "session"),
                     ci.lvl = 0.83)

lmer_vsl.effects <- data_vsl %>% 
  as_tibble() %>% 
  mutate(VSL = factor(group, labels = c("Low","Moderate","High")))

spline_vsl <- ggplot(lmer_vsl.effects, aes(x, predicted, ymin = conf.low, ymax = conf.high)) +
  geom_line(aes(linetype=VSL)) +
  scale_linetype_manual(values=c("solid", "longdash", "solid")) +
  scale_fill_manual(values = c("turquoise4", "tan1","black")) +
  geom_ribbon(aes(fill=VSL),alpha=0.5) +
  facet_grid(~facet) +
  ylab("Tactical Picture Error") +
  scale_y_continuous(breaks = c(0, 2000, 4000, 6000, 8000)) +
  xlab("Time [20s]") +
  theme_bw() +  
  theme(legend.position="top",        
        legend.text = element_text(size = 14),
        legend.title = element_text(size = 14),
        axis.title.x = element_text(size=16),
        plot.title = element_text(size=16, face="bold"),
        axis.title.y = element_text(size=16),
        axis.text.x = element_text(size=16),
        axis.text.y = element_text(size=16),
        strip.text.x = element_text(size = 14))

spline_vsl

# digit span / working memory
summary(d_tpe_final$DSpanScore)

lmer_dspan <- lmer(TPE ~ ns(Time, 4) * DSpanScore * session + decline + (1 | subj), data = d_tpe_final)
Anova(lmer_dspan)
summary(lmer_vsl)
model_performance(lmer_vsl)
check_model(lmer_vsl)

data_dspan <- ggemmeans(lmer_dspan,
                     terms = c("Time [all]", "DSpanScore [4.00, 6.00, 9.00]", "session"),
                     ci.lvl = 0.83)

lmer_dspan.effects <- data_dspan %>% 
  as_tibble() %>% 
  mutate(DS = factor(group, labels = c("Low","Moderate","High")))

spline_dspan <- ggplot(lmer_dspan.effects, aes(x, predicted, ymin = conf.low, ymax = conf.high)) +
  geom_line(aes(linetype=DS)) +
  scale_linetype_manual(values=c("solid", "longdash", "solid"), name ="DST") +
  scale_fill_manual(values = c("turquoise4", "tan1","black"), name ="DST") +
  geom_ribbon(aes(fill=DS),alpha=0.5) +
  facet_grid(~facet) +
  ylab("Tactical Picture Error") +
  scale_y_continuous(breaks = c(0, 2000, 4000, 6000, 8000)) +
  xlab("Time [20s]") +
  theme_bw() +  
  theme(legend.position="top",        
        legend.text = element_text(size = 14),
        legend.title = element_text(size = 14),
        axis.title.x = element_text(size=16),
        plot.title = element_text(size=16, face="bold"),
        axis.title.y = element_text(size=16),
        axis.text.x = element_text(size=16),
        axis.text.y = element_text(size=16),
        strip.text.x = element_text(size = 14))

spline_dspan

# mental rotation accuracy
summary(d_tpe_final$MR_ACC)

lmer_mr_acc <- lmer(TPE ~ ns(Time, 4) * MR_ACC * session + decline + (1 | subj), data = d_tpe_final)
Anova(lmer_mr_acc)
summary(lmer_mr_acc)
model_performance(lmer_mr_acc)
check_model(lmer_mr_acc)

data_mar_acc <- ggemmeans(lmer_mr_acc,
                     terms = c("Time [all]", "MR_ACC [0.44, 0.87, 0.95]", "session"),
                     ci.lvl = 0.83)

lmer_mr_acc.effects <- data_mar_acc %>% 
  as_tibble() %>% 
  mutate(MRA = factor(group, labels = c("Low","Moderate","High")))

spline_mra <- ggplot(lmer_mr_acc.effects, aes(x, predicted, ymin = conf.low, ymax = conf.high)) +
  geom_line(aes(linetype=MRA)) +
  scale_linetype_manual(values=c("solid", "longdash", "solid"), name = "MRT-A") +
  scale_fill_manual(values = c("turquoise4", "tan1","black"), name = "MRT-A") +
  geom_ribbon(aes(fill=MRA),alpha=0.5) +
  facet_grid(~facet) +
  ylab("Tactical Picture Error") +
  scale_y_continuous(breaks = c(0, 2000, 4000, 6000, 8000)) +
  xlab("Time [20s]") +
  theme_bw() +  
  theme(legend.position="top",        
        legend.text = element_text(size = 14),
        legend.title = element_text(size = 14),
        axis.title.x = element_text(size=16),
        plot.title = element_text(size=16, face="bold"),
        axis.title.y = element_text(size=16),
        axis.text.x = element_text(size=16),
        axis.text.y = element_text(size=16),
        strip.text.x = element_text(size = 14))

spline_mra

# mental rotation reaction time
summary(d_tpe_final$MR_RT)

lmer_mr_rt <- lmer(TPE ~ ns(Time, 4) * MR_RT * session + decline + (1 | subj), data = d_tpe_final)
Anova(lmer_mr_rt)
summary(lmer_mr_rt)
model_performance(lmer_mr_rt)
check_model(lmer_mr_rt)

data_mar_rt <- ggemmeans(lmer_mr_rt,
                     terms = c("Time [all]", "MR_RT [908.2, 3483.9, 5664]", "session"),
                     ci.lvl = 0.83)

lmer_mr_rt.effects <- data_mar_rt %>% 
  as_tibble() %>% 
  mutate(MRT = factor(group, labels = c("Fast","Moderate","Slow")))

spline_mrt <- ggplot(lmer_mr_rt.effects, aes(x, predicted, ymin = conf.low, ymax = conf.high)) +
  geom_line(aes(linetype=MRT)) +
  scale_linetype_manual(values=c("solid", "longdash", "solid"), name = "MRT-RT") +
  scale_fill_manual(values = c("turquoise4", "tan1","black"), name = "MRT-RT") +
  geom_ribbon(aes(fill=MRT),alpha=0.5) +
  facet_grid(~facet) +
  ylab("Tactical Picture Error") +
  scale_y_continuous(breaks = c(0, 2000, 4000, 6000, 8000)) +
  xlab("Time [20s]") +
  theme_bw() +  
  theme(legend.position="top",        
        legend.text = element_text(size = 14),
        legend.title = element_text(size = 14),
        axis.title.x = element_text(size=16),
        plot.title = element_text(size=16, face="bold"),
        axis.title.y = element_text(size=16),
        axis.text.x = element_text(size=16),
        axis.text.y = element_text(size=16),
        strip.text.x = element_text(size = 14)) +
  coord_cartesian(ylim = c(0, 9000))

spline_mrt

tiff("spline_lmer_models_behavioural.tiff", units="in", width=16, height=11, res=300)
ggarrange(spline_vsl, spline_dspan, spline_mra, spline_mrt,
          labels = c("A", "B", "C", "D"),
          ncol = 2, nrow = 2,
          common.legend = FALSE)
dev.off()

```

Let's see if we can plot the modelled results together with the raw data.

```{r basic_lmers_plot_with_raw_data}

raw_iaf <- d_tpe_final %>% 
  filter(Time > 500) %>%
  mutate(IAF = cut_interval(cog, n = 3, labels = c("Low","Moderate","High"))) %>% 
  group_by(Time,IAF) %>% 
  summarise(TPE_mean = mean(TPE))

raw_slope <- d_tpe_final %>% 
  filter(Time > 500) %>%
  mutate(Slope = cut_interval(Slope, n = 3, labels = c("Steep","Moderate","Flatter"))) %>% 
  group_by(Time,Slope) %>% 
  summarise(TPE_mean = mean(TPE))

raw_intercept <- d_tpe_final %>% 
  filter(Time > 500) %>%
  mutate(Intercept = cut_interval(Intercept, n = 3, labels = c("High","Moderate","Low"))) %>% 
  group_by(Time,Intercept) %>% 
  summarise(TPE_mean = mean(TPE))

ggplot(lmer_cog.effects, aes(x,predicted)) +
  geom_path(aes(colour = IAF)) +
  scale_linetype_manual(values=c("solid", "longdash", "solid")) +
  scale_fill_manual(values = c("turquoise4", "tan1","black")) +
  geom_ribbon(aes(fill = IAF, ymin = conf.low, ymax = conf.high), alpha = 0.3) +
  facet_grid(~facet) +
  ylab("Tactical Picture Error") +
  #scale_y_continuous(limits = c(0, 9000), breaks = seq(0, 9000, by = 1000)) +  
  xlab("Time [20s]") +
  geom_point(aes(Time,TPE_mean, colour = IAF), alpha = 0.4, size = 1, data = raw_iaf) +
  scale_color_manual(values=c("turquoise4", "tan1","black")) +
  theme_bw() +  theme(axis.title.x = element_text(size=14),
        plot.title = element_text(size=14, face="bold"),
        axis.title.y = element_text(size=14),
        axis.text.x = element_text(size=12),
        axis.text.y = element_text(size=12),
        strip.text.x = element_text(size = 13))

ggplot(lmer_slope.effects, aes(x,predicted)) +
  geom_path(aes(colour = Slope)) +
  scale_linetype_manual(values=c("solid", "longdash", "solid")) +
  scale_fill_manual(values = c("turquoise4", "tan1","black")) +
  geom_ribbon(aes(fill = Slope, ymin = conf.low, ymax = conf.high), alpha = 0.3) +
  facet_grid(~facet) +
  ylab("Tactical Picture Error") +
  #scale_y_continuous(limits = c(0, 9000), breaks = seq(0, 9000, by = 1000)) +  
  xlab("Time [20s]") +
  geom_point(aes(Time,TPE_mean, colour = Slope), alpha = 0.4, size = 1, data = raw_slope) +
  scale_color_manual(values=c("turquoise4", "tan1","black")) +
  theme_bw() +  theme(axis.title.x = element_text(size=14),
        plot.title = element_text(size=14, face="bold"),
        axis.title.y = element_text(size=14),
        axis.text.x = element_text(size=12),
        axis.text.y = element_text(size=12),
        strip.text.x = element_text(size = 13))

ggplot(lmer_intercept.effects, aes(x,predicted)) +
  geom_path(aes(colour = Intercept)) +
  scale_linetype_manual(values=c("solid", "longdash", "solid")) +
  scale_fill_manual(values = c("turquoise4", "tan1","black")) +
  geom_ribbon(aes(fill = Intercept, ymin = conf.low, ymax = conf.high), alpha = 0.3) +
  facet_grid(~facet) +
  ylab("Tactical Picture Error") +
  #scale_y_continuous(limits = c(0, 9000), breaks = seq(0, 9000, by = 1000)) +  
  xlab("Time [20s]") +
  geom_point(aes(Time,TPE_mean, colour = Intercept), alpha = 0.4, size = 1, data = raw_intercept) +
  scale_color_manual(values=c("turquoise4", "tan1","black")) +
  theme_bw() +  theme(axis.title.x = element_text(size=14),
        plot.title = element_text(size=14, face="bold"),
        axis.title.y = element_text(size=14),
        axis.text.x = element_text(size=12),
        axis.text.y = element_text(size=12),
        strip.text.x = element_text(size = 13))

```

```{r generate scatterplots between cognitive and neural metrics}

library(ggthemes)
library(ggeffects)
library(correlation)
library(see)
library(ggraph)

cor_data <- TPE_Grand %>%
  filter(session == "test") %>%
  select(-session, -TPE, -paf)

cor_data = subset(cor_data, select = -subj)

cor_data <- cor(cor_data)

col <- colorRampPalette(c("#BB4444", "#EE9988", "#FFFFFF", "#77AADD", "#4477AA"))
corrplot(cor_data, method="color", col=col(200),  
         type="upper", order="hclust", 
         addCoef.col = "black", # Add coefficient of correlation
         tl.col="black", tl.srt=45, #Text label color and rotation
         # Combine with significance
         # hide correlation coefficient on the principal diagonal
         diag=FALSE 
         )

cor_data_scatter <- TPE_Grand %>%
  filter(session == "test") %>%
  select(-session, -TPE, -paf)

cog.slope <- ggplot(cor_data_scatter, aes(Slope,cog)) +
  geom_point(shape=20, color="deepskyblue3", size = 5) +
  labs(y="Individual Alpha Frequency [Hz]", x = "Aperiodic (1/f) Slope") +
  geom_smooth(method=lm,  linetype="solid",
              color="gray48", fill="darkgrey") +
  scale_x_continuous(breaks = scales::pretty_breaks(n = 3)) +
  theme_light() +
  theme(axis.title.x = element_text(size=14),
        plot.title = element_text(size=14, face="bold"),
        axis.title.y = element_text(size=14),
        axis.text.x = element_text(size=12),
        axis.text.y = element_text(size=12))



cog.slope

cor.test(formula = ~ cog + Slope,
                          data = cor_data_scatter)


mass_flippers.lm <-  lm(cog ~ Slope, data=cor_data_scatter)
summary(mass_flippers.lm)

cor_data_scatter %>% 
  ggplot(aes(x=Slope,y=cog)) +
  geom_point() +
  geom_abline(intercept=coef(mass_flippers.lm)[1],slope=coef(mass_flippers.lm)[2])

mass_flippers.modelled <- mass_flippers.lm %>% 
  augment()

resid_iaf_plot <- mass_flippers.modelled %>% 
  ggplot(aes(x = Slope, y = cog)) +
  geom_smooth(method="lm", se=FALSE, colour="grey") +
  labs(y="Individual Alpha Frequency [Hz]", x = "Aperiodic (1/f) Slope") +
  geom_point(aes(colour=.resid, size=abs(.resid)), alpha=0.5) +
  scale_colour_gradient2(low="blue", mid="white", high="red") +
  geom_segment(aes(xend=Slope, yend=.fitted), alpha=0.5) +
  geom_point(aes(y = .fitted), shape=19, size = 3, alpha = 0.4) +
  guides(colour="none", size="none") +
  theme_light() +
  theme(axis.title.x = element_text(size=14),
        plot.title = element_text(size=14, face="bold"),
        axis.title.y = element_text(size=14),
        axis.text.x = element_text(size=12),
        axis.text.y = element_text(size=12))

##Age & IAF & 1/f
ages <- read.csv("final_analysis_demographics.csv", header = TRUE) %>%
  select(subj, age)

participants_list <- d_tpe_final[!duplicated(d_tpe_final$subj),] 
participants_list <- participants_list %>% select(subj, cog, Slope) 

iaf_slope <- left_join(ages, participants_list, by = "subj")

ggscatter(iaf_slope, x = "age", y = "Slope") +
  geom_smooth(method='lm', formula= y~x)
  
ggscatter(iaf_slope, x = "age", y = "cog")+
  geom_smooth(method='lm', formula= y~x)

```

```{r lmer outputs}
library(kableExtra)
library(lmerOut)

kable(Anova(lmer_cog), "latex", caption = "Summary of effects of IAF on TPE Scores (Type II Wald Tests)", booktabs = T) %>%
  save_kable("tables/iaf.pdf", keep_tex = TRUE)
pprint(lmer_cog, "tables/iaf_summary.tex")

kable(Anova(lmer_slope), "latex", caption = "Summary of effects of 1/f Slope on TPE Scores (Type II Wald Tests)", booktabs = T) %>%
  save_kable("tables/slope.pdf", keep_tex = TRUE)
pprint(lmer_slope, "tables/slope_summary.tex")

kable(Anova(lmer_intercept), "latex", caption = "Summary of effects of 1/f Intercept on TPE Scores (Type II Wald Tests)", booktabs = T) %>%
  save_kable("tables/intercept.pdf", keep_tex = TRUE)
pprint(lmer_intercept, "tables/intercept_summary.tex")

kable(Anova(lmer_vsl), "latex", caption = "Summary of effects of Visual Statistical Learning Ability on TPE Scores (Type II Wald Tests)", booktabs = T) %>%
  save_kable("tables/vsl.pdf", keep_tex = TRUE)
pprint(lmer_vsl, "tables/vsl_summary.tex")

kable(Anova(lmer_dspan), "latex", caption = "Summary of effects of Digit Span on TPE Scores (Type II Wald Tests)", booktabs = T) %>%
  save_kable("tables/dspan.pdf", keep_tex = TRUE)
pprint(lmer_dspan, "tables/dspan_summary.tex")

kable(Anova(lmer_mr_acc), "latex", caption = "Summary of effects of Mental Rotation Accuracy on TPE Scores (Type II Wald Tests)", booktabs = T) %>%
  save_kable("tables/nmra.pdf", keep_tex = TRUE)
pprint(lmer_mr_acc, "tables/mra_summary.tex")

kable(Anova(lmer_mr_rt), "latex", caption = "Summary of effects of Mental Rotation Reaction Time on TPE Scores (Type II Wald Tests)", booktabs = T) %>%
  save_kable("tables/mrt.pdf", keep_tex = TRUE)
pprint(lmer_mr_rt, "tables/mrt_summary.tex")

```
 
